name: build pull requests and branches

on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: install-jdk
        name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - id: setup-maven
        name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - id: maven-build
        name: Build with Maven
        run: mvn clean verify
        